import { 
  FaMoneyBillWave, 
  FaBriefcase, 
  FaBuilding, 
  FaPiggyBank, 
  FaLaptopCode, 
  FaChartLine, 
  FaGift, 
  FaEllipsisH, 
  FaHome, 
  FaUtensils, 
  FaCar, 
  FaFirstAid, 
  FaBook, 
  FaFilm, 
  FaCreditCard, 
  FaTshirt, 
  FaBath, 
  FaBaby, 
  FaPaw, 
  FaShieldAlt, 
  FaHandsHelping, 
  FaPlane, 
  FaEnvelopeOpenText, 
  FaBolt, 
  FaDumbbell, 
  FaMobileAlt, 
  FaHammer, 
  FaGavel, 
  FaGamepad, 
  FaGlassCheers, 
  FaBookOpen, 
  FaSeedling, 
  FaPaintBrush, 
  FaTools, 
  FaFireExtinguisher, 
  FaWrench, 
  FaTicketAlt, 
  FaCrown 
} from 'react-icons/fa';

export const categoryIcons = {
  // Income Categories
  'Salary / Wages': <FaMoneyBillWave style={{ color: '#00d0c2', width: 20, height: 20 }} />,
  'Business Income': <FaBriefcase style={{ color: '#00d0c2', width: 20, height: 20 }} />,
  'Freelance / Side Hustle': <FaLaptopCode style={{ color: '#00d0c2', width: 20, height: 20 }} />,
  'Rental Income': <FaBuilding style={{ color: '#00d0c2', width: 20, height: 20 }} />,
  'Pension': <FaPiggyBank style={{ color: '#00d0c2', width: 20, height: 20 }} />,
  'Investments / Dividends': <FaChartLine style={{ color: '#00d0c2', width: 20, height: 20 }} />,
  'Royalties': <FaCrown style={{ color: '#00d0c2', width: 20, height: 20 }} />,
  'Gift / Donations': <FaGift style={{ color: '#00d0c2', width: 20, height: 20 }} />,
  'Lottery Winnings': <FaTicketAlt style={{ color: '#00d0c2', width: 20, height: 20 }} />,
  'Government Benefits': <FaShieldAlt style={{ color: '#00d0c2', width: 20, height: 20 }} />,
  'Refunds / Rebates': <FaEnvelopeOpenText style={{ color: '#00d0c2', width: 20, height: 20 }} />,
  'Child Support / Alimony': <FaHandsHelping style={{ color: '#00d0c2', width: 20, height: 20 }} />,
  'Inheritance': <FaCrown style={{ color: '#00d0c2', width: 20, height: 20 }} />,
  'Selling Goods': <FaPiggyBank style={{ color: '#00d0c2', width: 20, height: 20 }} />,
  'Consulting Services': <FaLaptopCode style={{ color: '#00d0c2', width: 20, height: 20 }} />,
  'Interest Income': <FaPiggyBank style={{ color: '#00d0c2', width: 20, height: 20 }} />,
  'Bonus / Commission': <FaMoneyBillWave style={{ color: '#00d0c2', width: 20, height: 20 }} />,
  'Scholarships / Grants': <FaBook style={{ color: '#00d0c2', width: 20, height: 20 }} />,
  'Tax Refunds': <FaChartLine style={{ color: '#00d0c2', width: 20, height: 20 }} />,
  'Other Income': <FaEllipsisH style={{ color: '#00d0c2', width: 20, height: 20 }} />,

  // Expense Categories
  'Housing': <FaHome style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Utilities': <FaBolt style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Food & Groceries': <FaUtensils style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Transportation': <FaCar style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Health & Medical': <FaFirstAid style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Clothing & Accessories': <FaTshirt style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Personal Care': <FaBath style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Education': <FaBook style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Entertainment & Leisure': <FaFilm style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Dining Out': <FaUtensils style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Travel': <FaPlane style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Savings & Investments': <FaPiggyBank style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Insurance': <FaShieldAlt style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Debt Repayments': <FaCreditCard style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Subscriptions': <FaEnvelopeOpenText style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Charity': <FaHandsHelping style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Pets': <FaPaw style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Childcare': <FaBaby style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Sports & Fitness': <FaDumbbell style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Miscellaneous Expenses': <FaEllipsisH style={{ color: '#EF854B', width: 20, height: 20 }} />,
  'Other Expense': <FaEllipsisH style={{ color: '#EF854B', width: 20, height: 20 }} />,

  // Custom Categories
  'Home Improvement': <FaHammer style={{ color: '#77AA86', width: 20, height: 20 }} />,
  'Legal Fees': <FaGavel style={{ color: '#77AA86', width: 20, height: 20 }} />,
  'Gaming': <FaGamepad style={{ color: '#77AA86', width: 20, height: 20 }} />,
  'Festivals & Events': <FaGlassCheers style={{ color: '#77AA86', width: 20, height: 20 }} />,
  'Books & Magazines': <FaBookOpen style={{ color: '#77AA86', width: 20, height: 20 }} />,
  'Gardening': <FaSeedling style={{ color: '#77AA86', width: 20, height: 20 }} />,
  'Craft Supplies': <FaPaintBrush style={{ color: '#77AA86', width: 20, height: 20 }} />,
  'DIY Projects': <FaTools style={{ color: '#77AA86', width: 20, height: 20 }} />,
  'Vehicle Maintenance': <FaWrench style={{ color: '#77AA86', width: 20, height: 20 }} />,
  'Luxury Purchases': <FaCrown style={{ color: '#77AA86', width: 20, height: 20 }} />,
};


export const CATEGORIES = {
  income: [
    'Salary / Wages',
    'Business Income',
    'Freelance / Side Hustle',
    'Rental Income',
    'Pension',
    'Investments Dividends',
    'Royalties',
    'Gift / Donations',
    'Lottery Winnings',
    'Government Benefits',
    'Refunds / Rebates',
    'Child Support / Alimony',
    'Inheritance',
    'Selling Goods',
    'Consulting Services',
    'Interest Income',
    'Bonus / Commission',
    'Scholarships/ Grants',
    'Tax Refunds',
    'Other Income',
  ],
  expense: [
    'Housing',
    'Utilities',
    'Food & Groceries',
    'Transportation',
    'Health & Medical',
    'Clothing & Accessories',
    'Personal Care',
    'Education',
    'Entertainment & Leisure',
    'Dining Out',
    'Travel',
    'Savings & Investments',
    'Insurance',
    'Debt Repayments',
    'Subscriptions',
    'Charity',
    'Pets',
    'Childcare',
    'Sports & Fitness',
    'Miscellaneous Expenses',
    'Other Expense'
  ],
  other: [
    'Home Improvement',
    'Legal Fees',
    'Gaming',
    'Festivals & Events',
    'Books & Magazines',
    'Gardening',
    'Craft Supplies',
    'DIY Projects',
    'Vehicle Maintenance',
    'Luxury Purchases',
  ],
};

  